"""Catalog and pet subscriptions

Revision ID: 1d532c0cfeb8
Revises: 9184049026b0
Create Date: 2026-09-17 08:33:08.692801

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta


# revision identifiers, used by Alembic.
revision = '1d532c0cfeb8'
down_revision = '9184049026b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_plan_amount'),
    sa.CheckConstraint('duration_days > 0', name='ck_plan_duration'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_service_amount'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plan_benefits',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'service_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.CheckConstraint("source IN ('purchase', 'legacy', 'demo')", name='ck_subscription_source'),
    sa.CheckConstraint("status IN ('active', 'replaced', 'canceled')", name='ck_subscription_status'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_subscription_period'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_pet_id'), ['pet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_foreign_key('fk_appointments_subscription', 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_foreign_key('fk_payments_subscription', 'subscriptions', ['subscription_id'], ['id'])

    # Dados fixos nesta revisão: não importar o catálogo vivo da aplicação.
    bind = op.get_bind()
    metadata = sa.MetaData()
    tables = {name: sa.Table(name, metadata, autoload_with=bind) for name in (
        'plans', 'services', 'plan_benefits', 'subscriptions', 'pets', 'appointments', 'payments',
    )}
    plan_rows = [
        {'id': 'plan-basic', 'name': 'Básico', 'amount': 99, 'duration_days': 30},
        {'id': 'plan-premium', 'name': 'Premium', 'amount': 189, 'duration_days': 30},
        {'id': 'plan-premium-plus', 'name': 'Premium Plus', 'amount': 349, 'duration_days': 30},
    ]
    service_rows = [
        {'id': 'service-bath', 'name': 'Banho', 'amount': 60},
        {'id': 'service-grooming', 'name': 'Tosa', 'amount': 50},
        {'id': 'service-hydration', 'name': 'Hidratação', 'amount': 40},
        {'id': 'service-nail-cut', 'name': 'Corte de unha', 'amount': 20},
        {'id': 'service-ear-cleaning', 'name': 'Limpeza de ouvido', 'amount': 20},
    ]
    bind.execute(tables['plans'].insert(), plan_rows)
    bind.execute(tables['services'].insert(), service_rows)
    bind.execute(tables['plan_benefits'].insert(), [
        {'plan_id': plan['id'], 'service_id': service['id']}
        for plan in plan_rows for service in service_rows
        if plan['id'] == 'plan-premium-plus' or service['id'] in ('service-bath', 'service-grooming')
    ])
    # O legado não informa data nem compra do plano. Preservar como concessão
    # explícita de transição por 30 dias, sem inventar pagamentos históricos.
    now = datetime.utcnow()
    for pet in bind.execute(sa.select(tables['pets'])).mappings():
        plan = next((row for row in plan_rows if row['name'] == pet['plan']), None)
        if not plan:
            continue
        inserted = bind.execute(tables['subscriptions'].insert().values(
            store_id=pet['store_id'], pet_id=pet['id'], plan_id=plan['id'],
            starts_at=now, ends_at=now + timedelta(days=30), status='active', source='legacy',
        ))
        covered_services = [service['name'] for service in service_rows
                            if plan['id'] == 'plan-premium-plus'
                            or service['id'] in ('service-bath', 'service-grooming')]
        appointments = tables['appointments']
        payments = tables['payments']
        bind.execute(appointments.update().where(
            appointments.c.pet_id == pet['id'],
            appointments.c.store_id == pet['store_id'],
            appointments.c.service.in_(covered_services),
            appointments.c.scheduled_at < now + timedelta(days=30),
            ~sa.exists(sa.select(payments.c.id).where(payments.c.appointment_id == appointments.c.id)),
        ).values(subscription_id=inserted.inserted_primary_key[0]))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_payments_subscription', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_subscription_id'))
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_appointments_subscription', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointments_subscription_id'))
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_store_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_pet_id'))

    op.drop_table('subscriptions')
    op.drop_table('plan_benefits')
    op.drop_table('services')
    op.drop_table('plans')
    # ### end Alembic commands ###
