"""Enforce same store references

Revision ID: 73032ec89a26
Revises: 1d532c0cfeb8
Create Date: 2026-09-24 09:13:38.161886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73032ec89a26'
down_revision = '1d532c0cfeb8'
branch_labels = None
depends_on = None


def upgrade():
    # Refuse inconsistent legacy data before rebuilding any table.
    links = [
        ('pets', 'owner_id', 'users'),
        ('subscriptions', 'pet_id', 'pets'),
        ('appointments', 'client_id', 'users'),
        ('appointments', 'pet_id', 'pets'),
        ('appointments', 'subscription_id', 'subscriptions'),
        ('payments', 'client_id', 'users'),
        ('payments', 'confirmed_by_employee_id', 'users'),
        ('payments', 'appointment_id', 'appointments'),
        ('payments', 'subscription_id', 'subscriptions'),
    ]
    for child, column, parent in links:
        invalid = op.get_bind().execute(sa.text(
            f'SELECT c.id FROM {child} c LEFT JOIN {parent} p ON p.id = c.{column} '
            f'WHERE c.{column} IS NOT NULL AND (p.id IS NULL OR p.store_id <> c.store_id)'
        )).first()
        if invalid:
            raise RuntimeError(f'Referência inválida em {child}.{column}, registro {invalid[0]}. Corrija antes de migrar.')
    # Create parent candidate keys before child references.
    for table in ('users', 'pets', 'subscriptions', 'appointments'):
        with op.batch_alter_table(table) as batch_op:
            batch_op.create_unique_constraint(f'uq_{table}_id_store', ['id', 'store_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_appointments_subscription_store', 'subscriptions', ['subscription_id', 'store_id'], ['id', 'store_id'])
        batch_op.create_foreign_key('fk_appointments_client_store', 'users', ['client_id', 'store_id'], ['id', 'store_id'])
        batch_op.create_foreign_key('fk_appointments_pet_store', 'pets', ['pet_id', 'store_id'], ['id', 'store_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_payments_client_store', 'users', ['client_id', 'store_id'], ['id', 'store_id'])
        batch_op.create_foreign_key('fk_payments_appointment_store', 'appointments', ['appointment_id', 'store_id'], ['id', 'store_id'])
        batch_op.create_foreign_key('fk_payments_confirmer_store', 'users', ['confirmed_by_employee_id', 'store_id'], ['id', 'store_id'])
        batch_op.create_foreign_key('fk_payments_subscription_store', 'subscriptions', ['subscription_id', 'store_id'], ['id', 'store_id'])

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_pets_owner_store', 'users', ['owner_id', 'store_id'], ['id', 'store_id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_subscriptions_pet_store', 'pets', ['pet_id', 'store_id'], ['id', 'store_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_pet_store', type_='foreignkey')

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pets_owner_store', type_='foreignkey')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_subscription_store', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_confirmer_store', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_appointment_store', type_='foreignkey')
        batch_op.drop_constraint('fk_payments_client_store', type_='foreignkey')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_pet_store', type_='foreignkey')
        batch_op.drop_constraint('fk_appointments_client_store', type_='foreignkey')
        batch_op.drop_constraint('fk_appointments_subscription_store', type_='foreignkey')

    for table in ('appointments', 'subscriptions', 'pets', 'users'):
        with op.batch_alter_table(table) as batch_op:
            batch_op.drop_constraint(f'uq_{table}_id_store', type_='unique')

    # ### end Alembic commands ###
